class RoutePath {
  RoutePath._();
  static const String splash = '/';
  static const String signIn = '/sign-in';
  static const String signUp = '/sign-up';
  static const String home = '/home';
  static const String post = '/post';
  static const String notification = '/notification';
  static const String profile = '/profile';
  static const String search = '/search';
  static const String message = '/message';
  static const String video = '/video';
  static const String setting = '/setting';
  static const String editProfile = '/edit-profile';
  static const String changePassword = '/change-password';
  static const String createPost = '/create-post';
  static const String detailPost = '/detail-post';
  static const String editPost = '/edit-post';
  static const String detailUser = '/detail-user';
  static const String editUser = '/edit-user';
  static const String listUser = '/list-user';
  static const String listPost = '/list-post';
  static const String listComment = '/list-comment';
  static const String listNotification = '/list-notification';
  static const String listMessage = '/list-message';
  static const String listVideo = '/list-video';
  static const String listSetting = '/list-setting';
  static const String listEditProfile = '/list-edit-profile';
  static const String listChangePassword = '/list-change-password';
  static const String listCreatePost = '/list-create-post';
  static const String listDetailPost = '/list-detail-post';
  static const String listEditPost = '/list-edit-post';
  static const String listDetailUser = '/list-detail-user';
}
